apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civicpulse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/M-Hasaam/CivicPulse.git
    targetRevision: deploy/prod
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: civicpulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
